spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: hr

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 27cf5acf13b6396666e385cb79d41ed9
            client-secret: k3uxmZavDTQYYl8kkdFAsKIdTQoPDhFd
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ggamakun.linkle.domain
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: mySecretKeyForLinkleProjectThatIsLongEnoughForHS256AlgorithmToWorkProperly
  access-token-expiry: 3600000    # 1시간
  refresh-token-expiry: 604800000 # 1주일

oauth2:
  redirect:
    success-url: http://localhost:5173/auth/callback
    failure-url: http://localhost:5173/login?error=true